### ISSUE TITLE
Scripts to preprocess data

### ISSUE THREAD

**Issue by alomrani** [mismayil/crow#1]
Hi,

Thanks for pushing the repo. What scripts do you run to preprocess the dataset json files?

Thanks

**Comment by mismayil** [comment]
Hi there,

Do you refer to the original dataset files? If yes, you can find the preprocessing scripts under the first applied data collection stage folder (e.g. `ck_annotation`) for each task under the `mturk` folder. For example, for intent detection, you can find it [here](https://github.com/mismayil/crow/blob/main/mturk/intent_detection/ck_annotation/prepare_id_cka_data.py#L12) because full pipeline was applied to intent detection.

**Comment by alomrani** [comment]
> Hi there,
> 
> Do you refer to the original dataset files? If yes, you can find the preprocessing scripts under the first applied data collection stage folder (e.g. `ck_annotation`) for each task under the `mturk` folder. For example, for intent detection, you can find it [here](https://github.com/mismayil/crow/blob/main/mturk/intent_detection/ck_annotation/prepare_id_cka_data.py#L12) because full pipeline was applied to intent detection.

I get an error when calling prepare_id_cka_data.py on crow_intent.json (no 'writer_intent' in dataset json file). Do you have the pre-processed data json files?

**Comment by mismayil** [comment]
Oh, those files are the final public benchmark files. If you need the original dataset files, you can refer to each dataset link [here](https://www.mete.is/crow/tasks/). Under each task description, you will find links to original datasets.

**Comment by alomrani** [comment]
> Oh, those files are the final public benchmark files. If you need the original dataset files, you can refer to each dataset link [here](https://www.mete.is/crow/tasks/). Under each task description, you will find links to original datasets.

Thank you for the quick reply. Given these original dataset files, how do I regenerate your results?

**Comment by mismayil** [comment]
So, the thing is this benchmark is crowdsourced based on the existing datasets. So you can't really regenerate them:) What would you like to do with this benchmark?

**Comment by alomrani** [comment]
> So, the thing is this benchmark is crowdsourced based on the existing datasets. So you can't really regenerate them:) What would you like to do with this benchmark?

I see. I wanted to try a different prompting approach and compare it to yours.

**Comment by mismayil** [comment]
Yes, you can still do that with the public benchmark data. You have the context and the target for which you can prepare your custom prompt and get the results for the model. Once you have the results, you can submit them to us for evaluation [here](https://www.mete.is/crow/getting-started/).

**Comment by alomrani** [comment]
Ok thanks
